apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-estable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: estable
  template:
    metadata:
      labels:
        app: web
        version: estable
    spec:
      containers:
      - name: web-pink
        image: demo:v2   # Imagen que ya existe localmente
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
