apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-estable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: estable
  template:
    metadata:
      labels:
        app: web
        version: estable
    spec:
      containers:
      - name: web-red
        image: facuaavila5/imagen-red:v1 # <--- Imagen con fondo rojo
        ports:
        - containerPort: 80